#!/bin/sh

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
NC="\e[0m"

mem_info=$(free | awk '/Mem:/ {print $2, $3}')
set -- $mem_info
total=$1
used=$2
percent=$(awk "BEGIN {printf \"%.0f\", ($used/$total)*100}")

mem_total=$(free -h | awk '/Mem:/ {print $2}')
mem_used=$(free -h | awk '/Mem:/ {print $3}')
if [ -t 1 ]; then
  if [ "$percent" -le 60 ]; then
    percent_color=$GREEN
  elif [ "$percent" -le 80 ]; then
    percent_color=$YELLOW
  else
    percent_color=$RED
  fi
  echo "  ${mem_used} / ${mem_total} (${percent_color}${percent}%${NC})"
else
  echo "${mem_used} ${mem_total} ${percent}"
fi
