#! /bin/bash
set -e
pushd ~/dotfiles/nixos/
code configuration.nix
git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuilld switch &> ~/nixos-rebuild.log || ( cat nixos-rebuild.log | grep --color error && false )
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
popd
